### ISSUE TITLE
Exaples needed

### ISSUE THREAD

**Issue by blazeyzem** [sansil/m590#1]
Please provide some examples.

**Comment by sansil** [comment]
Hi blazeyzem,  I don't have a  "hello  world" example for this code, and i don't have plans to do one yet. 
On the other hand i can give you some spots to understand the code:
- I use threads using protothreads, you can get more information from this url: http://harteware.blogspot.com.uy/2010/11/protothread-powerfull-library.html
-  You can get m590 information from this url:
  http://docs.mirifica.eu/Neoway.com/archive/M590/
